project:
  type: website
  output-dir: docs

website:

  navbar:
    title: "<img src='img/logo.png' alt='Logo' class='logo' style='height: 50px; width: auto;'>"
    background: "white"
    foreground: "#a7a9ac"
    
    
    tools:
      - icon: facebook 
        href: https://www.facebook.com/profile.php?id=100093337606435
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/R-Ladies-Morelia/Reprohack2024/tree/main/Grupo2
            
  sidebar:
    style: "floating"
    foreground: "#a7a9ac"
    search: true
    alignment: right
    contents:
      - section: "Introducción"
        contents:
          - index.qmd
          - tema1.qmd
          - datos.qmd
          - information.qmd
      - section: "Revisión de temas"
        contents:
          - tema2.qmd
          - tema3.qmd
          - tema4.qmd
      - section: "Acerca de las funciones y figuras del artículo"
        contents:
          - tema5.qmd
          - tema6.qmd
          - retos.qmd
          - Figura1.qmd
          - Figura2.qmd
          - Figura3.qmd
          - Figura4.qmd
          - Figura5.qmd
          


format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    code-wrap: true
    message: false
    warning: false
    fig-height: 8
    fig-width: 8
    grid: 
      body-width: 1200px
      sidebar-width: 250px
      margin-width: 200px
      gutter-width: 0.8em
    fontsize: 14pt
  
engine: knitr
knitr:
  opts_chunk: 
    R.options:
      width: 120
